/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OnlineAdda;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Zobayer
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    boolean findChar(String s, char ch) {
        int conn = 0;
        for (int i = 0; i < s.length(); ++i) {
            if (s.charAt(i) == '@') ++conn;
        }
        if (conn == 1) return true;
        return false;
    } 
    Connection conn;
    Statement st;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fName = new javax.swing.JFormattedTextField();
        emailAdd = new javax.swing.JFormattedTextField();
        DOB = new javax.swing.JTextField();
        pWord = new javax.swing.JPasswordField();
        rpWord = new javax.swing.JPasswordField();
        register = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        jLabel1.setText("Sign Up");

        fName.setText("Enter your full name");
        fName.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        fName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fNameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fNameMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fNameMouseReleased(evt);
            }
        });
        fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameActionPerformed(evt);
            }
        });

        emailAdd.setText("Enter email");
        emailAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emailAddMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                emailAddMouseReleased(evt);
            }
        });
        emailAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAddActionPerformed(evt);
            }
        });

        DOB.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        DOB.setText("Date of Birth");
        DOB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DOBMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DOBMouseReleased(evt);
            }
        });

        pWord.setFont(new java.awt.Font("Serif", 1, 10)); // NOI18N
        pWord.setText("password");
        pWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pWordMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pWordMouseReleased(evt);
            }
        });

        rpWord.setFont(new java.awt.Font("Serif", 1, 10)); // NOI18N
        rpWord.setText("repasswo");
        rpWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rpWordMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rpWordMouseReleased(evt);
            }
        });

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rpWord, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pWord, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pWord, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rpWord, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameActionPerformed

    private void emailAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddActionPerformed

    private void fNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fNameMouseReleased
        // TODO add your handling code here:
        fName.setText(null);
    }//GEN-LAST:event_fNameMouseReleased

    private void emailAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailAddMouseReleased
        // TODO add your handling code here:
        emailAdd.setText(null);
    }//GEN-LAST:event_emailAddMouseReleased

    private void DOBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOBMouseReleased
        // TODO add your handling code here:
        DOB.setText(null);
    }//GEN-LAST:event_DOBMouseReleased

    private void pWordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pWordMouseReleased
        // TODO add your handling code here:
        pWord.setText(null);
    }//GEN-LAST:event_pWordMouseReleased

    private void rpWordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpWordMouseReleased
        // TODO add your handling code here:
        rpWord.setText(null);
    }//GEN-LAST:event_rpWordMouseReleased

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        String s1, s2, s3, s4, s5;
        s1 = String.valueOf(pWord.getPassword());
        s2 = String.valueOf(rpWord.getPassword());
        s3 = emailAdd.getText();
        s4 = fName.getText();
        s5 = DOB.getText();
        
        if (!s1.equals(s2)) {
            JOptionPane.showMessageDialog(null, "Password not match!");
        }
        else if(!findChar(s3, '@')) {
            JOptionPane.showMessageDialog(null, "Email is not correct");
        }
        else if (s4.equals("")) {
            JOptionPane.showMessageDialog(null, "Name is empty");
        }
        else if (s5.equals("")){
            JOptionPane.showMessageDialog(null, "Date of Birth is empty");
        }
        else {
            // Now all data can store in database
            String s = fName.getText();
            String p1 = String.valueOf(pWord.getPassword());
            
            try{
                conn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/massenger", "root", "seagoldbag");
                st = (com.mysql.jdbc.Statement) conn.createStatement();
                String sql = "insert into userlogin (ID, UserName, Password) values ('CSE', '"+s+"', '"+p1+"');";
                
                st.executeUpdate(sql);
                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "You are registered now.\nYou can log in.");
                
                login l = new login();
                l.setVisible(true);
                
                this.dispose();
                
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null, "User name alread have.\nTry different user name");
            }
        }
    }//GEN-LAST:event_registerActionPerformed

    private void fNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fNameMouseExited
        // TODO add your handling code here:
        String s = fName.getText();
        if (s.equals("")) {
            fName.setText("Enter your full name");
        }
    }//GEN-LAST:event_fNameMouseExited

    private void emailAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailAddMouseExited
        // TODO add your handling code here:
        String s = emailAdd.getText();
        if (s.equals("")) {
            emailAdd.setText("Enter email");
        }
    }//GEN-LAST:event_emailAddMouseExited

    private void DOBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOBMouseExited
        // TODO add your handling code here:
        String s = DOB.getText();
        if (s.equals("")) {
            DOB.setText("Date of Birth");
        }
    }//GEN-LAST:event_DOBMouseExited

    private void pWordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pWordMouseExited
        // TODO add your handling code here:
        String s = String.valueOf(pWord.getPassword());
        if (s.equals("")) {
            pWord.setText("password");
        }
    }//GEN-LAST:event_pWordMouseExited

    private void rpWordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpWordMouseExited
        // TODO add your handling code here:
        String s = String.valueOf(rpWord.getPassword());
        if (s.equals("")) {
            rpWord.setText("repasswo");
        }
    }//GEN-LAST:event_rpWordMouseExited

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        login l = new login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void fNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DOB;
    private javax.swing.JButton back;
    private javax.swing.JFormattedTextField emailAdd;
    private javax.swing.JFormattedTextField fName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField pWord;
    private javax.swing.JButton register;
    private javax.swing.JPasswordField rpWord;
    // End of variables declaration//GEN-END:variables
}
